services:
  home-kuma:
    image: louislam/uptime-kuma:beta 
    container_name: home-kuma
    restart: always
    volumes:
      - ${data_path}:/app/data
      - ${ca_path}:/certs/root_ca.crt
    networks:
      home-kuma:
      lan:
        ipv4_address: ${ip_address}
    environment:
      - NODE_EXTRA_CA_CERTS=/certs/root_ca.crt


networks:
  home-kuma:
    external: true
  lan:
    external: true
