services:
    home-dash:
        restart: unless-stopped
        container_name: home-dash
        image: b4bz/homer
        networks:
         - home-dash
        volumes:
          - /root/home-dash/www/assets:/www/assets

networks:
  home-dash:
    external: true