services:
  home-adguard:
    image: adguard/adguardhome
    container_name: home-adguard
    restart: unless-stopped
    volumes:
      - ${adguardhome_work_path}:/opt/adguardhome/work
      - ${adguardhome_conf_path}:/opt/adguardhome/conf
      - ${cert_path}:/cert
    networks:
      SDB1:
        ipv4_address: ${ip_address}


networks:
  SDB1:
    external: true
