---
- name: Basic Configuration for Debian Machines
  hosts: all
  remote_user: root
  vars:
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install git and curl
      apt:
        name:
          - git
          - curl
        state: present

    - name: Autoremove unused packages
      apt:
        autoremove: yes

    - name: Ensure PermitRootLogin is set correctly
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
        state: present
      notify: restart ssh

    - name: Ensure the SSH service is running and enabled
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Disable password authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: restart ssh

    - name: Check if Postfix is installed
      command: systemctl is-active postfix
      register: postfix_status
      changed_when: false
      failed_when: postfix_status.rc not in [0, 3, 4]  # 0 means active, 3 means inactive, 4 means service not found

    - name: stop and disable Postfix service if it exists
      service:
        name: postfix
        state: stopped
        enabled: no
      when: postfix_status.rc == 0

    - name: Uninstall Postfix if it exists
      apt:
        name: postfix
        state: absent
      when: postfix_status.rc == 0

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
